storage_adapters:
  dlx.security.user:
    class: Daikon\CouchDb\Storage\CouchDbStorageAdapter
    connector: dlx.security.event_store
    settings:
      design_doc: dlx-security-user

stream_stores:
  dlx.security.user:
    class: Daikon\CouchDb\Storage\CouchDbStreamStorage
    storage_adapter: dlx.security.user

units_of_work:
  dlx.security.user:
    class: Dailex\Infrastructure\DataAccess\UnitOfWork\UnitOfWork
    stream_store: dlx.security.user
    aggregate_root: Dlx\Security\User\Domain\User