dlx.security.event_store:
  connector: dailex.event_store
  settings:
    database: ${project.prefix}%2Bdlx-security

dlx.security.message_queue:
  connector: dailex.message_queue

dlx.security.message_queue.admin:
  connector: dailex.message_queue.admin

dlx.security.projection_store.standard:
  connector: dailex.projection_store.standard
  settings:
    index: ${project.prefix}.dlx-security

dlx.security.filesystem:
  connector: dailex.filesystem
  settings:
    mounts:
      migration:
        adapter: League\Flysystem\Adapter\Local
        location: ${app.base_dir}/vendor/dailex/dlx-security/migration